---
title: "First R Notebook"
author: "Mitri Traile"
date: "2024-10-15"
output: html_document
---
# install packages 
```{r}
# install.packages("tidyverse")
```

# load packages
```{r}
library(tidyverse)
```
# plot iris 
```{r}
ggplot(data=iris)+
  geom_point(mapping=aes(x=Petal.Width, y= Petal.Length, color=Species, size= Species, shape= Species))


ggplot(data=iris)+
  geom_line(mapping=aes(x= Sepal.Width, y= Sepal.Length, color= Species, size= Species, shape= Species))


ggplot(data=iris)+
  geom_col(mapping= aes(x= Species, y= Petal.Length), fill= "lightblue")+ theme_test()
```
# load class data
```{r}
savic=read_csv("class_data.csv")
```
# basic info
```{r}
nrow(savic)
ncol(savic)
colnames(savic)
mean (savic$correct)
```
# plot reaction time
```{r}
ggplot(data=savic)+
  geom_histogram (mapping=aes(x=as.numeric(rt)))
range(as.numeric(savic$rt))
```
```{r}

```
# tidyverse verbs 
```{r}
objectdata= read_csv("objects.csv")%>%
  mutate(rt= as.numeric(rt),
         weight= as.factor(weight),
         shape= as.factor(shape))
nrow("objects.csv")
ncol("objects.csv")
colnames("objects.csv")
condition_data= objectdata %>%
  filter(typeoftrial == "picture" & weight %in% c("Heavy", "Light") & 
  shape %in% c("Normal", "Smashed") &
  correct == TRUE) %>%
  select(subject,rt, weight, shape, correct)
condition_data %>%
  summarise(mean_rt = mean (rt))
object_agg = condition_data %>%
  group_by(weight,shape) %>%
  summarise(mean_rt = mean(rt),
            sd_rt= sd(rt))

ggplot(data= object_agg) +
  geom_col(mapping = aes(x= shape, y= mean_rt, fill= weight),
           position= "dodge") +
  theme_test()+ 
  labs(title= "plot of RTs")+
  scale_fill_manual(values= c("red", "skyblue"))
```
# class data analysis 
```{r}
savic=read_csv("class_data.csv")%>%
  mutate(rt=as.numeric(rt),
         relatedness= as.factor(relatedness),
         type= as.factor(type))
levels(savic$relatedness)
savic%>% group_by(ID) %>% count()

savic%>% filter(typeoftrial == "target") %>%
  group_by(ID) %>% count()
x= savic%>% filter(typeoftrial == "target") %>%
  group_by(ID) %>% count() %>%
  filter(n != 104)

mean(x$n)

savic%>% 
  filter(typeoftrial == "target") %>%
  pull(rt)

savic%>% 
  pull(ID) %>% unique() %>% length()
```
#attention 
```{r}
  attention_trials= savic%>%filter(typeoftrial == "attention") %>%
  select(ID,response,novel1,novel2,novel3,correct) %>%
rowwise() %>%
  mutate(response= ifelse(is.na(response), "blank", response)) %>%
  mutate(across(c(novel1, novel2, novel3), ~ replace_na(., "NOT_FOUND"))) %>%
  mutate(edit_novel1 = adist(novel1, response),
         edit_novel2= adist(novel2, response),
         edit_novel3= adist(novel3, response)) %>%
  mutate(revised_correct = ifelse(edit_novel1 <2|
                                    edit_novel2 <2 |
                                    edit_novel3 <2,
                                  1,0),
                        mismatch= ifelse(correct == revised_correct, 0,1)) %>%
           ungroup()
## mean 

attention_trials %>%
  summarize(mean_accuracy= mean (revised_correct),
            sd_accuracy= sd(revised_correct))

## summarize participant accuracy 
subject_attention_accuracy = attention_trials %>%
  group_by(ID) %>%
  summarize (mean_accuracy = mean (revised_correct))

##find IDs that have less than 75% accuracy

low_acc_IDs = subject_attention_accuracy %>%
  filter (mean_accuracy < 0.75) %>%
  pull(ID)
```

# priming analysis 

```{r}
priming_data= savic%>% filter(typeoftrial == "target") %>%
  select (ID, rt, relatedness, prime, response,type, correct, block_number, target, correct_key) %>%
  filter(!is.na(rt), rt> 200, rt< 1500, correct == "TRUE", block_number == 1) %>%
  filter(relatedness %in% c("related", "unrelated") & type %in% c("direct", "shared")) %>%
filter(!ID %in% low_acc_IDs)
```
## plot 
```{r}
priming_data %>%
  group_by(type, relatedness) %>%
  summarise(mean_rt = mean(rt)) %>%
  ggplot() +
  geom_col(mapping= aes(x= type, y= mean_rt, 
                        group= relatedness, fill= relatedness),
           position = "dodge") +
  theme_bw() +
  scale_fill_grey()
```
# linear models
```{r}
data(women)
women %>%
ggplot(aes(x=weight, y=height)) +
  geom_point()+
geom_smooth(method= "lm" )+
  theme_classic()
```

# load packages
```{r}
library(tidyverse)
```

```{r}
women %>%
ggplot(aes(x=weight, y=height)) +
  geom_point()+
geom_smooth(method= "lm" )+
  theme_classic()
women_model = lm(data = women,height ~weight)
summary(women_model)
```

#install car package
```{r}
#install.packages("car")
car:: Anova(women_model)
```
# iris again 
```{r}
data(iris)
View(iris)

iris%>%
  group_by(Species)%>%
  summarise(mean_length=mean(Petal.Length))

iris%>%
  ggplot(aes(x=Species, y=Petal.Length))+
geom_boxplot()+
theme_classic()
```
#ANOVA for iris 
```{r}
iris_model=lm(data = iris, Petal.Length~Species)
car:: Anova(iris_model)
```
Species sig predicted petal length, F(2,147) = 1180.2, p< 0.001
# install emmeans
```{r}
#install.packages("emmeans")
emmeans:: emmeans(iris_model,
                  pairwise~ Species,
                  adjust= "tukey")
```
Follow up tests indicate that setosa's petal length is sig diff from both versicolor (t(147)= -32.51, p<.001) and virginica(t(147)=-47.521, p<.0001)

```{r}
priming_data %>%
  group_by(ID,relatedness,type)%>%
  count()
```

